apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.0-devel
      command: [ "/bin/bash", "-c", "sleep 2147483647" ]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
    - name: digits-container
      image: nvidia/digits:6.0
      command: [ "/bin/bash", "-c", "sleep 2147483647" ]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
    - name: tensorflow-container
      image: tensorflow/tensorflow:latest-gpu
      command: [ "/bin/bash", "-c", "sleep 2147483647" ]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
