apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myelintek
  labels:
    app: myelintek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myelintek
  template:
    metadata:
      labels:
        app: myelintek
    spec:
      containers:
      - name: myelintek
        image: myelintek/web:dnnfarm-1.0
        command: [ "/bin/bash", "-c", "service ssh start;sh /usr/local/bin/digits-devserver; sleep 2147483647" ]
        ports:
        - containerPort: 22
        - containerPort: 80
        volumeMounts: 
        - name: nvidia-driver
          mountPath: /usr/local/nvidia
          readOnly: true
        - name: libcuda-so
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
        - name: libcuda-so-1
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
        - name: libcuda-so-384-66
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.384.81
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: {{.GpuCnt}}
      nodeSelector:
        gputype: v1004
      volumes:
      - name: nvidia-driver
        hostPath:
          path: /opt/nvidia
      - name: libcuda-so
        hostPath:
          path: /opt/nvidia/lib64/libcuda.so
      - name: libcuda-so-1
        hostPath:
          path: /opt/nvidia/lib64/libcuda.so.1
      - name: libcuda-so-384-66
        hostPath:
          path: /opt/nvidia/lib64/libcuda.so.384.81
---
apiVersion: v1
kind: Service
metadata:
  name: myelintek
  labels:
    app: myelintek
spec:
  ports:
  - name: ssh
    port: 22
  - name: web
    port: 80
  selector:
    app: myelintek
  type: NodePort
