apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: my-storage-class
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/data"
