kind: Pod
apiVersion: v1
metadata:
  name: phpfpm-nginx
  labels:
    app: phpfpm
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
    - image: my-php-app:1.0.0
      name: app
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
    - image: nginx:1.7.9
      ports:
      - containerPort: 80
      name: nginx
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: phpfpm-nginx
  labels:
    app: phpfpm
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: phpfpm
  type: NodePort
